# Generated by Django 2.2.6 on 2021-07-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=10)),
                ('first_name_kana', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('last_name_kana', models.CharField(max_length=10)),
                ('call_num', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
