# Generated by Django 2.2.6 on 2021-08-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='memo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='call_num',
            field=models.CharField(max_length=15, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='first_name',
            field=models.CharField(max_length=10, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='first_name_kana',
            field=models.CharField(max_length=10, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_name',
            field=models.CharField(max_length=10, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_name_kana',
            field=models.CharField(max_length=10, verbose_name=''),
        ),
    ]
